<a href="https://colab.research.google.com/github/sarathi-vs13/Deep-Learning/blob/main/Artificial_Neural_Network_(ANN)_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Modelling a single Neuron

In [25]:
import sys
import numpy as np
import matplotlib

In [26]:
#inputs = [1.0,2.0,3.0]
#weights  = [0.2,0.88,-0.5]
#bias = 2

In [27]:
#output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2]

In [28]:
output

array([[ 5.65,  4.75, -2.35],
       [ 3.6 ,  3.  ,  0.3 ],
       [ 3.4 ,  4.4 , -1.5 ]])

# Modelling a layer

In [29]:
inputs = [1.0,2.0,3.0,2.5]
weights1 = [0.2,0.1,0.5,0.7]
weights2 = [-0.2,-0.1,0.3,0.5]
weights3 = [0.2,0.1,-0.5,-0.7]
# number of biases will be same as number of neuron
bias1 = 2.0
bias2 = 3.0
bias3 = 0.4

In [30]:
output = [ inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2], inputs[3]*weights1[3]+bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2], inputs[3]*weights2[3]+bias2,
           inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2], inputs[3]*weights3[3]+bias3,
          ]

In [31]:
output

[1.9, 3.75, 0.4999999999999999, 4.25, -1.1, -1.35]

In [32]:
#instead we can use numpy to avoid repeating all the steps

In [33]:
inputs =[
    [1,2,3,2.5],
     [2.0,3.0,-1.0,2.0],
      [-1.5,0.0,2.0,1.0]]

weights = [
    [0.2, 0.1, 0.5, 0.7],   # weights for neuron 1
    [-0.2, -0.1, 0.3, 0.5], # weights for neuron 2
    [0.2, 0.1, -0.5, -0.7]  # weights for neuron 3
]
biases = [2,3,0.5]

In [34]:
#output = np.dot (np.array(weights),inputs) + biases
#print(output)

#np.dot(weights, inputs) won't work directly because the shapes are incompatible ((3, 4) dot (3, 4) is invalid).
# hence we need to transpose the second matrix(weights)


In [35]:
output = np.dot(inputs,np.array(weights).T) + biases
print(output)

[[ 5.65  4.75 -2.35]
 [ 3.6   3.    0.3 ]
 [ 3.4   4.4  -1.5 ]]


##Adding another layer

In [43]:
inputs =[
    [1,2,3,2.5],
     [2.0,3.0,-1.0,2.0],
      [-1.5,0.0,2.0,1.0]]

weights1 = [
    [0.2, 0.8, -0.5, 0.7],   # weights for neuron 1
    [-0.2, -0.1, 0.3, 0.5], # weights for neuron 2
    [0.2, 0.1, -0.5, -0.7]  # weights for neuron 3
]

weights2 = [
    [0.2, 0.1, -0.5],   # weights for neuron 1
    [-0.2, -0.5, 1.0], # weights for neuron 2
    [0.7, 0.1, -0.7]  # weights for neuron 3
]

biases1 = [2,3,0.5]
biases2 = [1,-2,0.5]

layer1_output = np.dot(inputs,np.array(weights1).T) + biases1
layer2_output = np.dot(layer1_output,np.array(weights2).T) + biases2


print(layer2_output)



[[ 3.46  -7.535  5.455]
 [ 2.49  -4.54   5.28 ]
 [ 2.47  -5.98   2.97 ]]


#Activation functions

##Step function
- The output is either 0 or 1

## Sigmoid function
- Output can be 0 to 1.
- Output can be different values
- Helpful with optimizers to finetune parameters ( weights and biases)

### Disadvantage:
 - Vanishing gradient problem
 - Not used in hidden layer and only used in Output layer



In [44]:
def step (inputs):
  output = np.zeros_like(inputs)
  output[np.array(inputs)>0] = 1
  return output

In [45]:
def sigmoid (inputs):
  output = 1/(1+np.exp(-np.array(inputs)))
  return output

##Understanding step and Sigmoid with simple example

In [50]:
import numpy as np

# Inputs
inputs = np.array([1.0, 2.0, 3.0])

# Weights and bias
weights = np.array([0.5, -0.6, 0.1])
bias = 1.5

z = np.dot(inputs, weights) + bias

def step_function(x):
    return 1 if x >= 0 else 0

output_step = step_function(z)
print("Output with Step Function:", output_step)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

output_sigmoid = sigmoid(z)
print("Output with Sigmoid Function:", output_sigmoid)


Output with Step Function: 1
Output with Sigmoid Function: 0.7502601055951177


Based on the results of the step/sigmoid we can increase or decrease the weights and bias

### ReLu function
- It checks the max between 0 and the value and returns 0 if its less than 0 and the value if its greater than 0.
- Output is more granular
- Non linear and can be used in hidden layers

##Disadvantages
 - Disables neagtives and can't be used for output nodes.

In [55]:
def relu(inputs):
  output = np.maximum(0,inputs)
  return output

relu([-1,4,-9,3,2])

array([0, 4, 0, 3, 2])

### Exponential
- Negatives are preserved
- Always non negative
- Zero for - inf
- 1 for zero
- Increases for positive values
## Disadvantages
- Very quickly the values gets so large(exponential increase)


### Softmax
- Normalize the values
- Divides each values by sum of all values

In [62]:
import numpy as np

logits = np.array([2.0, 1.0, 0.1,5,1.1])
exp_values = np.exp(logits)

print(exp_values)

Normalized_values = exp_values / np.sum(exp_values)

print(Normalized_values)


[  7.3890561    2.71828183   1.10517092 148.4131591    3.00416602]
[0.04543481 0.01671453 0.00679562 0.91258261 0.01847242]


In [63]:
sum(Normalized_values)

np.float64(1.0)