#First NN code

In [ ]:
import tensorflow as tf
print(tf.__version__)
import numpy as np
from tensorflow import keras

2.18.0


In [ ]:
#older way
#model = tf.keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])

model = tf.keras.Sequential([
    keras.layers.Dense(units=1, input_shape=[1])
])


In [ ]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [ ]:
#input and target data
x = np.array([-1,0.0,1.0,2.0,3.0], dtype=float)
y = np.array([-3,-1.0,3.0,5.0,7.0], dtype=float)

In [ ]:
model.fit(x,y,epochs=100,verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 1.8182
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1.6532
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 1.5090
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 1.3828
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 1.2723
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1.1755
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 1.0905
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.0158
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.9501
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.8922
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.8411
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.7959
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.7559
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.7204
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.6888
Epoch 16/100
1/1 ━━

In [ ]:
model.get_weights()

[array([[2.5025032]], dtype=float32), array([-0.16592485], dtype=float32)]

In [ ]:
print (model.predict(np.array([10.0])))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[[24.859108]]


In [ ]:
print (model.predict(np.array([20.0])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[49.88414]]


In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg = LinearRegression().fit(x.reshape(-1,1),y)

In [ ]:
reg.predict([[10]])

array([25.6])

In [ ]:
reg.predict([[20]])

array([51.6])

In [ ]:
reg.intercept_

np.float64(-0.3999999999999999)

In [ ]:
reg.coef_

array([2.6])

#Learning
Where does the actual learning happen?
It happens when we update the weight and Bias (Parameters)

##Analytical method
OLS method is one example. By solving the equation we try to find the weights and bias. But it gets extremely tough for equations with more variables.
It suffers in non linear equations.

## Numerical method
Iterative way of changing this weights and bias is the numerical method. Neural networks use this numerical approach.
They can compile parallelly. Meaning 1000 epochs can be given to 1000 computers to compile . It can easily handle non linear equations